### ISSUE TITLE
Support for Rhel9/ Predicatable interfaces

### ISSUE THREAD

**Issue by marty9x9** [amazonlinux/amazon-ec2-net-utils#103]
Does v1 work in RHEL 9 and Predicatable Network Interfaces?

**Comment by nmeyerhans** [comment]
What does RHEL 9 use for network interface configuration?  v1 targets a Amazon Linux 2, which is similar to RHEL/CentOS 7 in terms of interface management.  That is, it uses the old style initscripts network configuration system and ISC dhclient.  If RHEL 9 still uses that then maybe it works, but it is entirely untested and will likely require some modification. Alternatively, if RHEL 9 uses systemd-networkd, then it may be possible to make the it work, but again it's entirely untested in that environment.
