### ISSUE TITLE
1.x: Add optional provisioning of ipv4 delegated prefix IPs

### ISSUE THREAD

**Issue by jblosser** [amazonlinux/amazon-ec2-net-utils#57]
When support for prefix delegation was added to 1.x, it was limited to updating routing rules, with the comment "Assignment of individual addresses within the prefix is out of scope for this package, and would instead be handled by a local IPAM system.  A typical such system might provision IP addresses for use by locally running containers, etc."

The problem is that if we are using prefixes on e.g. an ec2 iptables NAT instance and provisioning IPs from the delegated range locally, they are removed whenever the ec2net functions run, multiple times an hour. It would be preferable if there was an option to have at least ipv4 addresses inside delegated prefixes detected and managed like other secondary addresses are.

PR incoming.

**Comment by nmeyerhans** [comment]
This will be included in an upcoming 1.7.0 release.
