### ISSUE TITLE
get_meta retry loop attempt not incrementing correctly

### ISSUE THREAD

**Issue by junhaohuang1** [amazonlinux/amazon-ec2-net-utils#81]
https://github.com/amazonlinux/amazon-ec2-net-utils/blob/57cc0e559a71a911f0e1831283237210bd5f2628/lib/lib.sh#L92

the attempts not getting incremented as expected.

Should be let attempts+=1 instead of  attempts+=1

for reference https://linuxhint.com/increment-a-variable-in-bash/

**Comment by nmeyerhans** [comment]
Thanks for reviewing the code! However, you're mistaken. attempts has been [declared as an integer earlier](https://github.com/amazonlinux/amazon-ec2-net-utils/blob/57cc0e559a71a911f0e1831283237210bd5f2628/lib/lib.sh#L78), meaning the increment operation as written is performed in an integer context and behaves as expected. You can test this behavior yourself pretty easily:

```bash
# This loop will increment and print the foo variable 10 times.
declare -i foo
foo=0
for i in {1..10}; do
  foo+=1
  echo $foo
done
```
