### ISSUE TITLE
The amazon-ec2-net-utils RPM package does not own the /usr/share/amazon-ec2-net-utils directory

### ISSUE THREAD

**Issue by keithaws** [amazonlinux/amazon-ec2-net-utils#84]
The `amazon-ec2-net-utils` RPM owns the file `/usr/share/amazon-ec2-net-utils/lib.sh`, but not the directory the file is in.

The spec file will need to be modified in order to correct this problem.

**Comment by halfdime-code** [comment]
Does this apply to all versions of the OS? AL1/2/2022?

**Comment by keithaws** [comment]
@halfdime-code: The file `/usr/share/amazon-ec2-net-utils/lib.sh` only exists in the 2.x version, so this will only impact AL2022.

**Comment by nmeyerhans** [comment]
Fixed with #85
