### ISSUE TITLE
Shellcheck error on Debian 12/bookworm (testing as of today)

### ISSUE THREAD

**Issue by nodakai** [amazonlinux/amazon-ec2-net-utils#88]
```
In lib/lib.sh line 402:
        registered=$?
                   ^-- SC2320 (warning): This $? refers to echo/printf, not a previous command. Assign to variable to avoid it being overwritten.
```

https://github.com/amazonlinux/amazon-ec2-net-utils/blob/dc1f1e9d659d3a4337f9337aa29ba85f49452eae/lib/lib.sh#L402

I'm not a Bash programming expert myself, I don't know if this is a genuine problem or a false alarm, but at least it broke the build

**Comment by nmeyerhans** [comment]
@nodakai Thanks for raising this! Will check it out.
