### ISSUE TITLE
Using device number from IMDS before propagation

### ISSUE THREAD

**Issue by atkinsam** [amazonlinux/amazon-ec2-net-utils#90]
When a secondary ENI is attached to an EC2 instance shortly after instance launch, setup_interface() in lib.sh will sometimes fetch the wrong device number from IMDS for the newly-attached interface. This results in conflicting default routes. 

There is a comment calling out this possibility in the start condition: https://github.com/amazonlinux/amazon-ec2-net-utils/blob/c71ae5dc8cd67d4eb7b4fc2bdbc2e6f5e63218b1/bin/setup-policy-routes.sh#L53-L55

But then in `setup_interface` we proceed to do exactly what we were supposed to avoid: 

https://github.com/amazonlinux/amazon-ec2-net-utils/blob/c71ae5dc8cd67d4eb7b4fc2bdbc2e6f5e63218b1/lib/lib.sh#L347

https://github.com/amazonlinux/amazon-ec2-net-utils/blob/c71ae5dc8cd67d4eb7b4fc2bdbc2e6f5e63218b1/lib/lib.sh#L360

This leads to identical eni.conf contents for the two interfaces:

```
[root@ip-172-31-65-182 ~]# cat /run/systemd/network/70-eth0.network.d/eni.conf
# Configuration for eth0 generated by policy-routes@eth0.service
[Match]
MACAddress=0e:63:0e:1f:54:e9
[Network]
DHCP=yes
[DHCPv4]
RouteMetric=512
[DHCPv6]
RouteMetric=512

[root@ip-172-31-65-182 ~]# cat /run/systemd/network/70-eth1.network.d/eni.conf
# Configuration for eth1 generated by policy-routes@eth1.service
[Match]
MACAddress=0e:62:4f:22:be:57
[Network]
DHCP=yes
[DHCPv4]
RouteMetric=512
[DHCPv6]
RouteMetric=512
```

And then conflicting default routes, which breaks a whole bunch of things.

```
[root@ip-172-31-65-182 ~]# ip route show table main to default
default via 198.19.64.1 dev eth0 proto dhcp src 198.19.93.32 metric 512
default via 10.0.32.1 dev eth1 proto dhcp src 10.0.34.196 metric 512
```

**Comment by nmeyerhans** [comment]
@atkinsam Thanks for the report.  Am I correct in assuming that this is happening on ENI hotplug, rather than at instance launch?

**Comment by atkinsam** [comment]
Yes that's right, only on ENI hotplug.

**Comment by nmeyerhans** [comment]
@atkinsam Are you able to test the change from https://github.com/amazonlinux/amazon-ec2-net-utils/compare/main...nmeyerhans:amazon-ec2-net-utils:device-number-propagation-fix?  You can simply replace the `lib.sh` file on an instance with the one from that branch.

**Comment by hughdanliu** [comment]
Ran a quick test - confirmed that implementing the change from https://github.com/amazonlinux/amazon-ec2-net-utils/compare/main...nmeyerhans:amazon-ec2-net-utils:device-number-propagation-fix resolved this issue:
```
[root@ip-198-19-118-31 /]# cat /run/systemd/network/70-eth0.network.d/eni.conf
# Configuration for eth0 generated by policy-routes@eth0.service
[Match]
MACAddress=0e:72:04:5d:a4:b9
[Network]
DHCP=yes
[DHCPv4]
RouteMetric=512
[DHCPv6]
RouteMetric=512
[root@ip-198-19-118-31 /]# cat /run/systemd/network/70-eth1.network.d/eni.conf
# Configuration for eth1 generated by policy-routes@eth1.service
[Match]
MACAddress=0e:4b:cf:d7:3c:69
[Network]
DHCP=yes
[DHCPv4]
RouteMetric=522
[DHCPv6]
RouteMetric=522
[Route]
Table=10001
Gateway=_ipv6ra
[DHCPv4]
RouteTable=10001
[IPv6AcceptRA]
RouteTable=10001
[Route]
Gateway=_dhcp4
Table=10001
```

```
[root@ip-198-19-118-31 /]# ip route show table main to default
default via 198.19.96.1 dev eth0 proto dhcp src 198.19.118.31 metric 512 
```

**Comment by nmeyerhans** [comment]
Thank you for confirming.  I'll be putting together a pull request in the near future and will include this fix in it.

Out of curiosity, what distro are you using?  The use of `eth0` suggests that it's not Amazon Linux 2023 or Debian 12, which is where I'm primarily testing this.

**Comment by hughdanliu** [comment]
I am using AL2023, but I’ve supplied the kernel parameter net.ifnames=0 to disable predictable network interface names, as instructed here: https://wiki.debian.org/NetworkInterfaceNames#:~:text=The%20simple%20way%20of%20disabling,grub%20and%20running%20update%2Dgrub.
